# Fetching the latest node image on alpine linux
FROM node:18-alpine

# Setting up the work directory
WORKDIR /freeze

# Installing dependencies
COPY ./package*.json ./

RUN npm install

# Copying all the files in our project
COPY . .

# Expose the port your app runs on
EXPOSE 3000

# Starting our application
CMD ["npm","start"]